apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: my-webapp
          image: avi9800/webapp:master
          ports:
            - containerPort: 8082
      imagePullSecrets:
        - name: my-secret

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30002
  type: NodePort